networks:
  my_network:
    driver: bridge


volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/miguiji/data/wordpress
      o: bind

  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/miguiji/data/mariadb
      o: bind

services:


  nginx:
    env_file: ".env"
    container_name: nginx
    image: nginx:miguiji
    build: ./requirements/nginx/
    volumes:
      - wordpress:/var/www/html
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - my_network
    restart: unless-stopped


  wordpress:
    container_name: wordpress
    image: wordpress:miguiji
    build: ./requirements/wordpress/
    env_file: ".env"
    expose:
      - 9000
    volumes:
      - wordpress:/var/www/html
    networks:
      - my_network
    depends_on :
      - mariadb
      - redis
    restart: unless-stopped



  mariadb:
    container_name: mariadb
    env_file: ".env"
    image: mariadb:miguiji
    build: requirements/mariadb/
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - my_network
    restart: unless-stopped



  redis:
    container_name: redis
    image: redis:miguiji
    build: ./requirements/bonus/redis/
    volumes:
      - redis
    networks:
      - my_network
    restart: unless-stopped


  adminer:
    container_name: adminer
    image: adminer:miguiji
    build: ./requirements/bonus/adminer/
    networks:
      - my_network
    ports:
      - 8000:8000
    restart: unless-stopped


  website:
    container_name: website
    image: website:miguiji
    build: ./requirements/bonus/website/
    networks: 
      - my_network
    ports:
      - 8080:8080
    restart: unless-stopped


  portainer:
    container_name: portainer
    image: portainer:miguiji
    env_file: ".env"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    build: requirements/bonus/portainer/
    networks:
      - my_network
    ports:
      - "9000:9000"
    restart: unless-stopped


  ftp:
    container_name: ftp
    image: ftp:miguiji
    build: requirements/bonus/ftp/
    env_file: ".env"
    volumes:
      - wordpress:/home/admin/
    networks:
      - my_network
    ports:
      - "20:20"
      - "21:21"
    restart: unless-stopped
